### ISSUE TITLE
Writing Modules Documentation

### ISSUE THREAD

**Issue by Havvy** [cjones/madcow#13]
There doesn't seem to be any documentation on writing modules, and what functions are available for modules.

For instance, I cannot find out how to send a message to a specified channel. I see there's a response method, but these messages aren't in response to a query, so...

**Comment by cjones** [comment]
in general the response goes back to the channel or user that initiated the request in the first place. Do you need to send output to a different channel than from whence it originated? This seems odd to me but if you really need to, you can modify kwargs['channel'] before returning the response. The value works like IRC PRIVMSG, meaning that despite the name "channel", this controls whether it goes to a channel or directly to a user via private message based entirely on whether it begins with a #. in other words the channel "foo" is user foo, the channel #foo is an actual public channel #foo. There are a few other mutable values in the dictionary you can change but glancing at it I don't think any are useful, and are passed in largely for the benefit of a module that needs more context to handle the request properly.

In any event, this isn't documented partly because it's a weird edge case -- the intended API is returning a line of text, which goes back to wherever it came. This is mostly what people want it to do. Also, there ... isn't really any documentation at all to begin with besides installation instructions. Contributions are certainly welcome.
